CREATE SCHEMA IF NOT EXISTS mitre;
CREATE SCHEMA IF NOT EXISTS tara;

CREATE TABLE IF NOT EXISTS mitre.techniques (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mitre.mitigations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mitre.dfds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mitre.dfd_technique (
    dfd_id BIGINT NOT NULL REFERENCES mitre.dfds(id) ON DELETE CASCADE,
    technique_id TEXT NOT NULL REFERENCES mitre.techniques(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (dfd_id, technique_id)
);

CREATE TABLE IF NOT EXISTS mitre.mitigation_technique (
    mitigation_id TEXT NOT NULL REFERENCES mitre.mitigations(id) ON DELETE CASCADE,
    technique_id TEXT NOT NULL REFERENCES mitre.techniques(id) ON DELETE CASCADE,
    m_description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (mitigation_id, technique_id)
);

CREATE TABLE IF NOT EXISTS mitre.dfd_techniques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    asset TEXT NOT NULL,
    parent TEXT NOT NULL DEFAULT '',
    step_name TEXT NOT NULL,
    inferred_tactic_id TEXT,
    inferred_tactic TEXT,
    technique_id TEXT NOT NULL REFERENCES mitre.techniques(id) ON DELETE CASCADE,
    technique_name TEXT NOT NULL,
    technique_tactics TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mitre_dfd_techniques
        UNIQUE (category, asset, parent, step_name, technique_id)
);

CREATE TABLE IF NOT EXISTS mitre.ttp_scoring (
    technique_id TEXT PRIMARY KEY REFERENCES mitre.techniques(id) ON DELETE CASCADE,
    "Proximity" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Locality" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Restoration Costs" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Impact_C" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Impact_I" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Impact_A" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Prior Use" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Required Skills" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Required Resources" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Stealth" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    "Attribution" NUMERIC(10, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mitre.ttp_scoring_reason (
    technique_id TEXT PRIMARY KEY REFERENCES mitre.techniques(id) ON DELETE CASCADE,
    reason_proximity TEXT,
    reason_locality TEXT,
    reason_restoration_costs TEXT,
    reason_impact_c TEXT,
    reason_impact_i TEXT,
    reason_impact_a TEXT,
    reason_prior_use TEXT,
    reason_required_skills TEXT,
    reason_required_resources TEXT,
    reason_stealth TEXT,
    reason_attribution TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tara.tara_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    entry_asset TEXT NOT NULL,
    target_asset TEXT NOT NULL,
    cia_attribute TEXT,
    damage_scenario TEXT,
    impact_category TEXT,
    threat_scenario TEXT,
    attack_path JSONB,
    attack_feasibility TEXT,
    impact_rating TEXT,
    risk_treatment TEXT,
    cal_rating TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mitre_techniques_name
    ON mitre.techniques (name);

CREATE INDEX IF NOT EXISTS idx_mitre_mitigations_name
    ON mitre.mitigations (name);

CREATE INDEX IF NOT EXISTS idx_mitre_dfds_name
    ON mitre.dfds (name);

CREATE INDEX IF NOT EXISTS idx_mitre_dfd_technique_technique_id
    ON mitre.dfd_technique (technique_id);

CREATE INDEX IF NOT EXISTS idx_mitre_mitigation_technique_technique_id
    ON mitre.mitigation_technique (technique_id);

CREATE INDEX IF NOT EXISTS idx_mitre_dfd_techniques_asset_step
    ON mitre.dfd_techniques (asset, step_name);

CREATE INDEX IF NOT EXISTS idx_mitre_dfd_techniques_technique_id
    ON mitre.dfd_techniques (technique_id);

CREATE INDEX IF NOT EXISTS idx_tara_assessments_session_id
    ON tara.tara_assessments (session_id);

CREATE INDEX IF NOT EXISTS idx_tara_assessments_created_at
    ON tara.tara_assessments (created_at DESC);
